<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Portfolio.Components.Messaging" Version="1.0.0" />
    <PackageReference Include="Portfolio.Components.Hosting" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Promo.Api.Domain\Promo.Api.Domain.csproj" />
  </ItemGroup>

</Project>
